### ISSUE TITLE
Windows 10 N64TOOL issue?

### ISSUE THREAD

**Issue by thekovic** [jnmartin84/64doom#15]
I am trying to create a ROM as per the instructions in the README but I am getting an N64TOOL error. It says to check for other on-screen error messages but there are none so I have no idea what the issue might be.

![image](https://user-images.githubusercontent.com/72971433/168657580-9095e8b6-aab1-4c54-8ac5-4ca74191790e.png)

**Comment by ProxyCell** [comment]
Hi @thekovic 
I can confirm this on my own end too.

I ran this in windows 10 64bit
XP 32bit

I tried it out in Win98SE and it threw up a cygwin error so thats probably a shortcoming of Win98SE/cygwin so lets ignore this one...

**Comment by jnmartin84** [comment]
Ok so the first thing is I realize now that I see this, that I forgot to update the text of some error message(s).

N64TOOL is newtool.exe in the repo tools folder/build zip file.

**Comment by jnmartin84** [comment]
I spent some time trying to debug the builder stuff because I've been getting other messages about it.

The only reason I've been able to determine for failures is if you edit make_doom.sh and modify ROOTDIR so it isn't "." anymore, that will mess up the entire script pretty reliably.

So don't do that, and if you did by chance, change it back and see if it starts to work. 

Otherwise, what is the filesize of your DOOM2.WAD ?

**Comment by jnmartin84** [comment]
Also wondering if I packaged a 64-bit cygwin dll / binaries and you're running on 32-bit Windows. 

I basically packaged this stuff up and pushed it in the spirit of sharing because Doom is open-source but I'll be honest, the builder stuff was even more of an after-thought than the rest of the repo.

If anyone wants to make a 32-bit version, I don't even have a 32-bit Windows system to attempt it.

**Comment by thekovic** [comment]
To provide more information, I am running MAKE_DOOM.bat on 64-bit Windows 10 21H2; not 32-bit. I have not edited make_doom.sh in any way, the whole repo is exactly as I cloned it from here.

I have also tried running make_doom.sh directly from the terminal of my own installation of msys2 (as opposed to the bash.exe, etc. that you shipped) but that results in the same error.

![image](https://user-images.githubusercontent.com/72971433/185116048-3caa3d4d-b837-4be2-a920-04d600d8cc43.png)

![image](https://user-images.githubusercontent.com/72971433/185116213-2c91877a-8ef4-4151-87b2-adc7910c6c13.png)

**Comment by thekovic** [comment]
I decided to compile my own version of newtool.exe from the newtool.c source file using my installation of msys2. After I removed the calls to fsync, I was able to compile what I assume is a fully native version of newtool, independant of cygwin's POSIX emulation layer which I am now able to run. When I execute make_doom.bat with this new newtool in place, I get a new error:
![image](https://user-images.githubusercontent.com/72971433/185146203-a9225826-b9b3-40d7-a35a-931dc3650512.png)

**Comment by jnmartin84** [comment]
I don't have and am not going to be installing mingw/msys2 so I can't really help with that but the error message implies newtool isn't seeing the expected number of command line arguments. I've seen some things through a quick google search that suggest in certain mixed version environments it just reports 0 for argc.

https://github.com/msys2/MSYS2-packages/issues/2198

No idea if that is what you are running into.

I tried to make this push-button but honestly if you reallllllly want it to be easy, grab the latest libdragon main branch, build the tools, and use n64tool.exe with the parameters you see in that newtool command and it'll probably just work.

**Comment by jnmartin84** [comment]
Maybe just try opening cmd.exe and running the newtool command without using make_doom.bat / make_doom.sh , see if there is any difference in result.

**Comment by thekovic** [comment]
If you had looked at the picture I sent in my last reply, you would have noticed that I was already running the tool in cmd.exe, thus it's not an msys2 enviroment bug. 

The error is thrown by the following part of code (newtool.c; lines 37 - 41):
```
if((argc - 10)%3)
	{
		printf("invalid number of arguments\n");
		exit(-1);
	}
```
If you look at make_doom.sh and count the number of arguments, you will find that `argc = 20` which results in `(20-10)%3 = 10%3 = 1` which means the program will fail and exit.

Removing the `-v` from the list of arguments would appear to be the solution, however that results in the following error:

![image](https://user-images.githubusercontent.com/72971433/185213773-b8aa5bb9-b533-49e1-a862-f3316f267fa7.png)

**Comment by jnmartin84** [comment]
Ok so you really didn't read what I wrote at all:
I said run newtool.exe directly from the cmd.exe prompt, you are still running make_doom.bat .

 but let me double-check if that is even the right source code in the repo for that tool.

**Comment by thekovic** [comment]
make_doom.bat just runs make_doom.sh which in turn just calls newtool.exe with predefined command line arguments, as opposed to whatever other arguments. I don't know what you're hoping to achieve from me running it just like `./newtool.exe`.

Doesn't matter anyway, I managed to fix the newtool myself and create a ROM. I can submit a pull request

**Comment by jnmartin84** [comment]
What I was hoping to achieve was to see if there were different results when not running it under bash but you kept ignoring the nuance. Glad you got it working for yourself

**Comment by altiereslima** [comment]
> make_doom.bat just runs make_doom.sh which in turn just calls newtool.exe with predefined command line arguments, as opposed to whatever other arguments. I don't know what you're hoping to achieve from me running it just like `./newtool.exe`.
> 
> Doesn't matter anyway, I managed to fix the newtool myself and create a ROM. I can submit a pull request

Could you release your altered files so I can compile doom?

**Comment by thekovic** [comment]
> > make_doom.bat just runs make_doom.sh which in turn just calls newtool.exe with predefined command line arguments, as opposed to whatever other arguments. I don't know what you're hoping to achieve from me running it just like `./newtool.exe`.
> > Doesn't matter anyway, I managed to fix the newtool myself and create a ROM. I can submit a pull request
> 
> Could you release your altered files so I can compile doom?

I did, check out #16

**Comment by ShinmaNoKodou** [comment]
I'm still getting that N64TOOL failed to execute error even with your changes. 
Can someone just like... PM the compiled N64 ROMs?  I'll even host them myself. I don't care.

**Comment by Colinsky123** [comment]
I'm experiencing the same error when attempting to build the game with any of my doom wad files.

64DOOM ROM BUILDER -- jnmartin84
Enter the number of the ROM to build:
1) Shareware
2) Registered
3) Ultimate
4) Doom 2
5) Plutonia
6) TNT
4
You chose Doom 2.
Using IDENTIFIER FILE ./identifiers/identifier_DOOM2
DOOM2.WAD
Using WADFILE ./wadfiles/DOOM2.WAD

Removing old Z64 file
./rm: cannot remove `DOOM2.Z64': No such file or directory
Executing: ./newtool -l 32M -h header -o DOOM2.Z64 -t "DOOM2" doom.bin -v -s 1048576B ./ADoom_Ins/MIDI_Instruments -s 5242880B ./identifiers/identifier_DOOM2 -s 5242896B ./wadfiles/DOOM2.WAD
^
|
|
---- !!!     POSSIBLE ERROR MESSAGE     !!!
     !!!          DO NOT IGNORE         !!!
     !!! SEE BELOW OUTPUT FOR MORE INFO !!!

N64TOOL failed to execute properly.
Check for other on-screen error messages and try again.


I've already been playing an older build for a while (built a few years ago), which I love, but thought I'd give your newer work a try but I just cannot get it to make the z64 file, using either the master or the fixed rom generation issue releases. I'm sure it's something simple with the newtool application, though I don't possess the know-how to fix it. Appreciate you're very busy, but if this can be looked at some point that'd be awesome!

**Comment by Yuraconst** [comment]
there's also an issue with cygbash in w10
Overall, please provide not Windows binaries but a "workie" - a VM image as binary release.

The age of coexistent executables is long gone.

**Comment by jnmartin84** [comment]
I am not supporting any kind of tooling for making ROMS anymore. 

I don't have resources or bandwidth for the troubleshooting.

The repo is in good shape and everything builds out of the box with a normal libdragon setup, so considering this and any related issues or PR closed.
