### ISSUE TITLE
Top beveled edge takes palette changes from item pickup if message on screen

### ISSUE THREAD

**Issue by thekovic** [jnmartin84/64doom#24]
![image](https://github.com/jnmartin84/64doom/assets/72971433/6a0bdc2c-2d71-468f-a528-f7b73f6c04b8)

**Comment by jnmartin84** [comment]
I am also aware of this, this is the result of an incomplete fix for those parts not getting drawn when the HUD got erased.

I got rid of the back-screen filling using the 256 color buffers altogether and I wasn't thorough enough trying to piece it back together with new code.

Working on this.

**Comment by jnmartin84** [comment]
fixed
