### ISSUE TITLE
Built ROM doesn't function on RetroArch cores

### ISSUE THREAD

**Issue by drisc** [jnmartin84/64doom#35]
I've tried building the game with multiple WADs now, all of which fail to launch on RetroArch with the ParaLLEl N64 and get as far as the screenshot below on Mupen64Plus-Next.
![image](https://github.com/jnmartin84/64doom/assets/2449110/afb9da61-e22f-4e00-be7e-3b817d8e665b)

There are no logs in the RetroArch logs folder so I can't provide them.

The built ROM does however play using the emulator Simple64: https://github.com/simple64/simple64

**Comment by thekovic** [comment]
Clearly an emulation issue on the part of Mupen64Plus-Next. The game works on accurate emulators like ares or mentioned simple64 and on real hardware.
