### ISSUE TITLE
Windows compatibility issues

### ISSUE THREAD

**Issue by ProxyCell** [jnmartin84/64doom#4]
Can you please confirm which version of windows you have this running on please?
I've used your previous 2014 version successfully and I was thrilled to see a new release with enhancements but this is not working for me on Windows 10 64 bit today.

I tried this with the BAT file and that failed, it complained about an incompatible version of cygwin1.dll in x:\cygwin\bin - this is despite the fact that the same dll file is in the directory itself as well as in c:\cygwin\bin

I figured it was a 32/64bit issue so I installed both and it still fails with the same error message.

Now I figure I should just run the .SH file from within cygwin but it appears that my cygwin installation isn't working properly either and I can not figure out why just yet. I have reinstalled it dozens of times and its not working on either 32 or 64 bit with vastly different errors on both.

I'm not even able to get to the numbered menu to select which game to build. I see you have made another commit since the release but I'm confident it is not that significant.

**Comment by jnmartin84** [comment]
this sounds like a issue on your end
