### ISSUE TITLE
Fix for Windows Compatability Issues

### ISSUE THREAD

**Issue by Magstriker** [jnmartin84/64doom#9]
I am running this on Windows 10 64bit for reference.

Please mention in the readme that in order for this to work on windows if you are getting a "'\r': command not found" error on multiple lines you must open MAKE_DOOM.sh in Notepad++ navigate to Edit->EOL Conversion->Unix then save the file and run MAKE_DOOM.bat and make sure you put your wads in the wadfiles directory.

**Comment by jnmartin84** [comment]
resolved

**Comment by BopItFreak** [comment]
Still getting this error on latest commit
